/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crypto_cipher_OpeNative */

#ifndef _Included_crypto_cipher_OpeNative
#define _Included_crypto_cipher_OpeNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     crypto_cipher_OpeNative
 * Method:    nativeEncrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_crypto_cipher_OpeNative_nativeEncrypt
  (JNIEnv *, jobject, jstring, jstring, jint, jint);

/*
 * Class:     crypto_cipher_OpeNative
 * Method:    nativeDecrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_crypto_cipher_OpeNative_nativeDecrypt
  (JNIEnv *, jobject, jstring, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
