/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crypsis_OPE */

#ifndef _Included_crypsis_OPE
#define _Included_crypsis_OPE
#ifdef __cplusplus
extern "C" {
#endif
#undef crypsis_OPE_SYMMETRIC_ENCRYPTION
#define crypsis_OPE_SYMMETRIC_ENCRYPTION 0L
#undef crypsis_OPE_ASYMMETRIC_ENCRYPTION
#define crypsis_OPE_ASYMMETRIC_ENCRYPTION 1L
#undef crypsis_OPE_PLAINTEXT_BITS
#define crypsis_OPE_PLAINTEXT_BITS 64L
#undef crypsis_OPE_CIPHERTEXT_BITS
#define crypsis_OPE_CIPHERTEXT_BITS 96L
/*
 * Class:     crypsis_OPE
 * Method:    encrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_crypsis_OPE_encrypt
  (JNIEnv *, jobject, jstring, jstring, jint, jint);

/*
 * Class:     crypsis_OPE
 * Method:    decrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_crypsis_OPE_decrypt
  (JNIEnv *, jobject, jstring, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
